version: '3.8'
services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5435:5432'
    volumes:
      # init database
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  data-volume:
